In [ ]:
import numpy as np
from numpy.linalg import *

In [ ]:
# PCA With 3 features

A=np.array([[4,8,13,7],[11,4,5,14],[2,3,4,5]])
A

array([[ 4,  8, 13,  7],
       [11,  4,  5, 14],
       [ 2,  3,  4,  5]])

In [ ]:
xmean=np.mean(A[0])
ymean=np.mean(A[1])

#Incase of 3*3
zmean=np.mean(A[2])
N=len(A[0])
N

4

In [ ]:
s=np.cov(A)
s

array([[ 14.        , -11.        ,   2.33333333],
       [-11.        ,  23.        ,   1.66666667],
       [  2.33333333,   1.66666667,   1.66666667]])

In [ ]:
values,vectors=eig(s)
vectors


array([[-0.55709406,  0.7557635 , -0.34419143],
       [ 0.83044423,  0.50552597, -0.23410655],
       [ 0.00293148,  0.41625115,  0.90924495]])

In [ ]:
e=vectors[0] if values[0]>values[1]  and values[0]else vectors[1]
e

array([-0.55709406,  0.7557635 , -0.34419143])

In [ ]:
new=[]
for i in range(0,N):
  #Incase of 3*3
  new.append(e@np.array([A[0][i]-xmean,A[1][i]-ymean,A[2][i]-zmean]))

  #Incase of 2*2
  #new.append(e@np.array([A[0][i]-xmean,A[1][i]-ymean]))
new


[4.63407212961279, -3.2288400486005284, -5.602738263342765, 4.197506182330503]

In [ ]:
e=vectors[1]
new=[]
for i in range(0,N):
  #Incase of 3*3
  new.append(e@np.array([A[0][i]-xmean,A[1][i]-ymean,A[2][i]-zmean]))

  #Incase of 2*2
  #new.append(e@np.array([A[0][i]-xmean,A[1][i]-ymean]))
new

[-1.7068021643518556,
 -2.157813589399303,
 2.2658269733752303,
 1.5987887803759289]

In [ ]:
temp=np.transpose(np.matrix([[-4,2.5]]))
np.matrix([[-0.5574,-0.8303]])@temp

matrix([[0.15385]])