In [47]:
from numpy import array
from scipy.linalg import svd

A = array([[1, 2],[2,1]])
U, s, VT = svd(A)
S = np.diag(s)

print("Given Matrix :\n",A,"\n")
print("Left Singluar Vectors :\n",VT,"\n")
print("Singluar Values :\n",S,"\n")
print("Right Singluar Vectors :\n",U,"\n")
print("Output :\n",U@S@VT)

Given Matrix :
 [[1 2]
 [2 1]] 

Left Singluar Vectors :
 [[-0.71 -0.71]
 [0.71 -0.71]] 

Singluar Values :
 [[3.00 0.00]
 [0.00 1.00]] 

Right Singluar Vectors :
 [[-0.71 -0.71]
 [-0.71 0.71]] 

Output :
 [[1.00 2.00]
 [2.00 1.00]]
